build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "John Doe - QA Lead"
    email: "john.qa@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1235