spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/yakoubOuldbouchiba/eazybank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
        #  search-locations: "file:////Users/oby/Documents/config/eazybank"
        #search-locations: "classpath:/config"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8071
encrypt:
  key: "EABCDE12345680JKLN"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true